In [2]:
import pandas as pd
import numpy as np

In [10]:
titanic_df = pd.read_csv('./titanic/train.csv')
print('titanic 변수 type:',type(titanic_df))

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


In [13]:
print('1.---------------------------------------------------')
titanic_df

1.---------------------------------------------------


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [84]:
print('2.---------------------------------------------------')
titanic_df.head(3)

2.---------------------------------------------------


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [87]:
titanic_df.drop(['PassengerId', 'Survived', 'Pclass'], axis = 1)

Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 9 columns]

In [17]:
print('3.---------------------------------------------------')
print('DataFrame 크기: ', titanic_df.shape)

3.---------------------------------------------------
DataFrame 크기:  (891, 12)


In [19]:
print('4.---------------------------------------------------')
titanic_df.describe()

4.---------------------------------------------------


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [24]:
print('5.---------------------------------------------------')
titanic_df['Pclass'].value_counts()

5.---------------------------------------------------


3    491
1    216
2    184
Name: Pclass, dtype: int64

In [26]:
titanic_df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [28]:
titanic_df[['Pclass', 'Sex']].value_counts()

Pclass  Sex   
3       male      347
        female    144
1       male      122
2       male      108
1       female     94
2       female     76
dtype: int64

In [30]:
print('6.---------------------------------------------------')
titanic_df['Pclass']

6.---------------------------------------------------


0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [32]:
type(titanic_df['Pclass'])

pandas.core.series.Series

In [35]:
print('7.---------------------------------------------------')
titanic_df['Pclass'].head()

7.---------------------------------------------------


0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [37]:
print('8.---------------------------------------------------')
titanic_df['Pclass'].value_counts()

8.---------------------------------------------------


3    491
1    216
2    184
Name: Pclass, dtype: int64

In [39]:
type(titanic_df['Pclass'].value_counts())

pandas.core.series.Series

In [42]:
col_name1=['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape )

array1 shape: (3,)


In [45]:
print('1.---------------------------------------------------')
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n')
df_list1

1.---------------------------------------------------
1차원 리스트로 만든 DataFrame:



col1
0     1
1     2
2     3

In [47]:
print('2.---------------------------------------------------')
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n')
df_array1

2.---------------------------------------------------
1차원 ndarray로 만든 DataFrame:



col1
0     1
1     2
2     3

In [49]:
print('3.---------------------------------------------------')
col_name2=['col1', 'col2', 'col3']
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:')
array2.shape

3.---------------------------------------------------
array2 shape:


(2, 3)

In [51]:
print('4.---------------------------------------------------')
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n')
df_list2

4.---------------------------------------------------
2차원 리스트로 만든 DataFrame:



col1  col2  col3
0     1     2     3
1    11    12    13

In [53]:
print('5.---------------------------------------------------')
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n')
df_array2

5.---------------------------------------------------
2차원 ndarray로 만든 DataFrame:



col1  col2  col3
0     1     2     3
1    11    12    13

In [55]:
print('6.---------------------------------------------------')
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n')
df_dict

6.---------------------------------------------------
딕셔너리로 만든 DataFrame:



col1  col2  col3
0     1     2     3
1    11    22    33

In [59]:
print('7.---------------------------------------------------')
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
array3

7.---------------------------------------------------
df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)


array([[ 1,  2,  3],
       [11, 22, 33]], dtype=int64)

In [61]:
print('8.---------------------------------------------------')
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

8.---------------------------------------------------
df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]


In [63]:
print('9.---------------------------------------------------')
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

9.---------------------------------------------------

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [65]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [66]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
concat1 = np.concatenate((arr1, arr2), axis = 0)
# 0이 가장 높은 차수로써 행을 의미
concat1

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
concat2 = np.concatenate((arr1, arr2), axis = -1)
# 음수로 가면 -1이 가장 낮은 차수로 열을 의미
concat2

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [79]:
concat3 = np.concatenate((arr1, arr2), axis = 1)
concat3

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [83]:
concat4 = np.concatenate((arr1, arr2), axis = 2)
concat4

AxisError: axis 2 is out of bounds for array of dimension 2

In [81]:
concat5 = np.concatenate((arr1, arr2), axis = -2)
concat5

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])