In [44]:
import tensorflow as tf

# 상수 노드 정의
a = tf.constant(1.0)
b = tf.constant(2.0)
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])

print('a :', a)
print('a + b :', a + b)
print('c :', c)

a : Tensor("Const_39:0", shape=(), dtype=float32)
a + b : Tensor("add_25:0", shape=(), dtype=float32)
c : Tensor("Const_41:0", shape=(2, 2), dtype=float32)


In [45]:
sess = tf.compat.v1.Session()
# sess = tf.compat.v1.Session()
# 구버전의 경우 세션 생성하는 방법이 살짝 다름

print('sess.run([a, b])\n',sess.run([a, b]), '\n')
print('sess.run(c)\n', sess.run(c), '\n')
print('sess.run([a + b])\n', sess.run([a + b]), '\n')
print('sess.run(c + 1.0)\n', sess.run(c + 1.0), '\n') # broadcast 실행

# 세션 close
sess.close()

sess.run([a, b])
 [1.0, 2.0] 

sess.run(c)
 [[1. 2.]
 [3. 4.]] 

sess.run([a + b])
 [3.0] 

sess.run(c + 1.0)
 [[2. 3.]
 [4. 5.]] 



In [46]:
# TensorFlow 읽어 들이기
import tensorflow as tf

# 상수 정의
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

# 연산 정의
calc1_op = a + b * c
calc2_op = (a + b) * c

# 세션 시작
sess = tf.compat.v1.Session()

res1 = sess.run(calc1_op) # 식 평가
res2 = sess.run(calc2_op) # 식 평가

print('res1\n', res1)
print('res2\n', res2)

sess.close()
# 이미 상수로 지정 되어있기 때문에 따로 값을 대입해야하는 식이 필요

res1
 14
res2
 20


In [47]:
import tensorflow as tf

# 플레이스홀더 노드 정의
a = tf.compat.v1.placeholder(tf.float32)
b = tf.compat.v1.placeholder(tf.float32)
c = a + b

# 세션 생성 후 플레이스홀도 노드를 통해 값 입력 받기
sess = tf.compat.v1.Session()

print('a: 1.0 / b: 3.0\n', sess.run(c, feed_dict={
  a: 1.0,
  b: 3.0
}))

print('a: [1.0, 2.0] / b: [3.0, 4.0]\n', sess.run(c, feed_dict={
  a: [1.0, 2.0],
  b: [3.0, 4.0]
}))

sess.close()
# 실행시키는 시점에서 값을 지정하기 때문에 사용에 용이

a: 1.0 / b: 3.0
 4.0
a: [1.0, 2.0] / b: [3.0, 4.0]
 [4. 6.]


In [48]:
import tensorflow as tf

# 플레이스홀더 노드 정의
a = tf.compat.v1.placeholder(tf.int32, [3]) # 정수 자료형 3개를 가진 배열

# 배열을 모든 값을 2배하는 연산 정의
b = tf.constant(2)
x2_op = a * b

# 세션 시작
sess = tf.compat.v1.Session()

# 플레이스홀더에 값을 넣고 실행
r1 = sess.run(x2_op, feed_dict={
  a: [1, 2, 3]
})

r2 = sess.run(x2_op, feed_dict={
  a: [10, 20, 30]
})

print('a: [1, 2, 3] * 2(tf.constant(2))\n', r1)
print('a: [10, 20, 30] * 2(tf.constant(2))\n', r2)

a: [1, 2, 3] * 2(tf.constant(2))
 [2 4 6]
a: [10, 20, 30] * 2(tf.constant(2))
 [20 40 60]


In [49]:
import tensorflow as tf

# 값이 업데이트 되는 변수 노드 정의
W1 = tf.Variable(tf.random.normal([1]))
b1 = tf.Variable(tf.random.normal([1]))
W2 = tf.Variable(tf.random.normal([1, 2]))
b2 = tf.Variable(tf.random.normal([1, 2]))

# 세션 시작
sess = tf.compat.v1.Session()

# 변수 노드 값 초기화 (변수 노드를 정의했다면 반드시 필요)
# 아래의 문구를 만나야 값이 초기화됨
sess.run(tf.compat.v1.global_variables_initializer())

for step in range(3):
  W1 = W1 - step
  b1 = b1 - step
  W2 = W2 - step
  b2 = b2 - step

  print('step =', step, 'W1 =', sess.run(W1), 'b1 =', sess.run(b1))
  print('step =', step, 'W2 =', sess.run(W2), 'b2 =', sess.run(b2), '\n')

sess.close()

step = 0 W1 = [0.07271298] b1 = [0.82371455]
step = 0 W2 = [[-1.1237509   0.38796976]] b2 = [[ 0.5807562  -0.35156935]] 

step = 1 W1 = [-0.92728704] b1 = [-0.17628545]
step = 1 W2 = [[-2.123751   -0.61203027]] b2 = [[-0.4192438 -1.3515694]] 

step = 2 W1 = [-2.927287] b1 = [-2.1762855]
step = 2 W2 = [[-4.1237507 -2.6120303]] b2 = [[-2.4192438 -3.3515694]] 



In [50]:
import tensorflow as tf

# feeding 값 선언
input_data = [1, 2, 3, 4, 5]

# placeholder 변수 선언
x = tf.compat.v1.placeholder(dtype=tf.float32)

# W = 2라는 값 선언
W = tf.Variable([2], dtype=tf.float32)
y = W * x

sess = tf.compat.v1.Session()

# 변수 초기화 코드를 세션에 전달
sess.run(tf.compat.v1.global_variables_initializer())
# y 그래프에 input_date feeding하면서 세션을 실행

result = sess.run(y, feed_dict={
  x: input_data
})

print(result)

sess.close()

[ 2.  4.  6.  8. 10.]


In [51]:
import tensorflow as tf

# 상수 정의
# name을 이용해서 별칭 부여 가능
a = tf.constant(10)
b = tf.constant(10)
c = tf.constant(20)

# 변수 정의
# 변수 v를 정의하고 초기값 0을 저장
v = tf.Variable(0)

# 데이터 플로우 그래프 정의
calc_op = a + b * c
assign_op = tf.compat.v1.assign(v, calc_op)

# 세션 실행
sess = tf.compat.v1.Session()

# tf.global_variables_initializer()
# 메소드를 사용하여 세션에 초기화 연산을 수행해야 하며,
# 변수에 메모리를 할당하고 초기값을 설정하는 역할을 한다.
sess.run(tf.compat.v1.global_variables_initializer())
sess.run(assign_op)

# v 내용 출력
print(sess.run(v))

sess.close()

210


In [52]:
import pandas as pd
import numpy as np
import tensorflow as tf

# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어오기
csv = pd.read_csv('bmi.csv')

# 데이터 정규화
csv['height'] = csv['height'] / 200
csv['weight'] = csv['weight'] / 100

# 레이블을 배열로 변환 (원-핫 인코딩 방식과 동일)
# thin=(1, 0, 0) / normal=(0, 1, 0) / fat=(0, 0, 1)
bclass = {
  'thin': [1, 0, 0],
  'normal': [0, 1, 0],
  'fat': [0, 0, 1]
}

csv['label_pat'] = csv['label'].apply(lambda x : np.array(bclass[x]))

# 테스트를 위한 데이터 분류
test_csv = csv[15000 : 20000]

test_pat = test_csv[['weight', 'height']]

test_ans = list(test_csv['label_pat'])

In [53]:
# 플레이스홀더 선언
x = tf.compat.v1.placeholder(tf.float32, [None, 2]) # 키와 몸무게 데이터 넣기 (2차원 구조)
y_ = tf.compat.v1.placeholder(tf.float32, [None, 3])

# 변수 선언
W = tf.Variable(tf.zeros([2, 3])) # 가중치
b = tf.Variable(tf.zeros([3])) # 바이어스

# 소프트맥스 회귀 정의
# tf.matmul() : 행렬 곱셈 함수
# tf.nn.softmax() : 다중 행렬 연산 함수
y = tf.nn.softmax(tf.matmul(x, W) + b)

# 모델 훈련
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=y, labels=y_))

# GradientDescentOptimizer
# 경사하강법으로 손실 함수를 최소화하는 모델 파라미터를 찾기 위해 사용
# 0.01은 학습률을 의미
optimizer = tf.compat.v1.train.GradientDescentOptimizer(0.01) # W와 b를 자동으로 설정
train = optimizer.minimize(cross_entropy)

# 정답률 구하기
predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(predict, tf.float32)) # tf.cast() : 캐스트 연산에 사용

sess = tf.Session()

sess.run(tf.compat.v1.global_variables_initializer()) # 변수 초기화

In [54]:
# 학습시키기
for step in range(20000):
  i = (step * 100) % 15000

  rows = csv[1 + i : 1 + i + 100]

  x_pat = rows[["weight","height"]]
  y_ans = list(rows["label_pat"])

  fd = {x: x_pat, y_: y_ans}

  sess.run(train, feed_dict=fd)

  if step % 500 == 0:
    cre = sess.run(cross_entropy, feed_dict=fd)
    acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})

    print("step=", step, "cre=", cre, "acc=", acc)

# 최종적인 정답률 구하기
acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})

print("\n정답률 =", acc)

# 세션 close
sess.close()

# step= 0 cre= 1.098595 acc= 0.3242
# step= 500 cre= 1.0949001 acc= 0.3684
# step= 1000 cre= 1.0968362 acc= 0.3684
# step= 1500 cre= 1.0890875 acc= 0.3684
# step= 2000 cre= 1.0854574 acc= 0.3684
# step= 2500 cre= 1.0907798 acc= 0.3684
# ...
# step= 19000 cre= 1.0012985 acc= 0.6926
# step= 19500 cre= 0.97811395 acc= 0.6926

# 정답률 = 0.6926

step= 0 cre= 1.098595 acc= 0.3242
step= 500 cre= 1.0949001 acc= 0.3684
step= 1000 cre= 1.0968362 acc= 0.3684
step= 1500 cre= 1.0890875 acc= 0.3684
step= 2000 cre= 1.0854574 acc= 0.3684
step= 2500 cre= 1.0907798 acc= 0.3684
step= 3000 cre= 1.0794799 acc= 0.3772
step= 3500 cre= 1.0763575 acc= 0.4024
step= 4000 cre= 1.082489 acc= 0.433
step= 4500 cre= 1.0693377 acc= 0.4796
step= 5000 cre= 1.0670123 acc= 0.5142
step= 5500 cre= 1.0734547 acc= 0.5468
step= 6000 cre= 1.058941 acc= 0.5828
step= 6500 cre= 1.0574982 acc= 0.6054
step= 7000 cre= 1.064285 acc= 0.6246
step= 7500 cre= 1.0485251 acc= 0.6442
step= 8000 cre= 1.0479634 acc= 0.6528
step= 8500 cre= 1.0552124 acc= 0.659
step= 9000 cre= 1.038259 acc= 0.6674
step= 9500 cre= 1.0385478 acc= 0.6726
step= 10000 cre= 1.0463612 acc= 0.6774
step= 10500 cre= 1.0282755 acc= 0.6812
step= 11000 cre= 1.02937 acc= 0.683
step= 11500 cre= 1.0378207 acc= 0.6846
step= 12000 cre= 1.018677 acc= 0.6868
step= 12500 cre= 1.0205232 acc= 0.6872
step= 13000 cre= 1.02