# 단순 선형 회귀 예제 (입력 변수 1개)

In [72]:
import numpy as np

x_data = np.array([1, 2, 3, 4, 5]).reshape(5,1) # 입력데이터 초기화
t_data = np.array([2, 3, 4, 5, 6]).reshape(5,1) # 정답데이터 초기화

W = np.random.rand(1,1) # 가중치 W 초기화
b = np.random.rand(1) # 바이어스 b 초기화

W, b
# (array([[0.05967214]]), array([0.11268206]))

(array([[0.53996599]]), array([0.59369211]))

In [73]:
# 손실 함수
def loss_func(x, t):
    y = np.dot(x,W) + b
    return (np.sum((t - y)**2 )) / (len(x))

In [74]:
# 수치 미분 함수
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index 
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x + delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    return grad

In [75]:
learning_rate = 1e-2 # 학습률 a

f = lambda x: loss_func(x_data, t_data)

print("Initial loss value = ",
      loss_func(x_data, t_data),
      "Initial W = ",
      W,
      "\n",
      ", b = ",
      b )

for step in range(9001):
    W -= learning_rate * numerical_derivative(f, W) # 손실 함수, 가중치
    b -= learning_rate * numerical_derivative(f, b) # 손실 함수, 바이어스
    if (step % 300 == 0): # 추가 부분
        print("step = ",
              step,
              "loss value = ",
              loss_func(x_data, t_data),
              "W =",
              W,
              "b =",
              b)

Initial loss value =  3.6145229357319204 Initial W =  [[0.53996599]] 
 , b =  [0.59369211]
step =  0 loss value =  2.132139976708165 W = [[0.66555195]] b = [0.62188515]
step =  300 loss value =  0.001924234835808365 W = [[1.02848563]] b = [0.89718302]
step =  600 loss value =  0.0002442889163523659 W = [[1.01014959]] b = [0.96336572]
step =  900 loss value =  3.101340519466074e-05 W = [[1.00361636]] b = [0.98694699]
step =  1200 loss value =  3.937269509115222e-06 W = [[1.00128853]] b = [0.99534914]
step =  1500 loss value =  4.998513091388735e-07 W = [[1.00045911]] b = [0.99834287]
step =  1800 loss value =  6.345802101422349e-08 W = [[1.00016358]] b = [0.99940956]
step =  2100 loss value =  8.056236639596324e-09 W = [[1.00005829]] b = [0.99978962]
step =  2400 loss value =  1.0227698209751372e-09 W = [[1.00002077]] b = [0.99992504]
step =  2700 loss value =  1.2984451096616812e-10 W = [[1.0000074]] b = [0.99997329]
step =  3000 loss value =  1.6484253526625665e-11 W = [[1.00000264]] 

In [76]:
def predict(x): # 예측 함수
    y = np.dot(x,W) + b
    return y

predict(np.array([43])) # 예축 테스트
# array([44.])

array([44.])

# `np.nditer` 예제

In [50]:
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(A, '\n')
print('A.shape ==', A.shape, '\n')

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
    idx = it.multi_index
    print(idx, 'current value =>', A[idx])
    it.iternext()

[[1 2 3 4]
 [5 6 7 8]] 

A.shape == (2, 4) 

(0, 0) current value => 1
(0, 1) current value => 2
(0, 2) current value => 3
(0, 3) current value => 4
(1, 0) current value => 5
(1, 1) current value => 6
(1, 2) current value => 7
(1, 3) current value => 8


# 다중 선형 회귀 예제 (입력 변수 1개)

In [81]:
import numpy as np

loaded_data = np.loadtxt('./data_01.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[:, 0:-1]
t_data = loaded_data[:, [-1]]

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)
loaded_data

x_data.ndim =  2 , x_data.shape =  (9, 3)
t_data.ndim =  2 , t_data.shape =  (9, 1)


array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.]], dtype=float32)

In [82]:
W = np.random.rand(3,1) # 가중치 W 초기화
b = np.random.rand(1) # 바이어스 b 초기화

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)
# 가중치 W, 바이어스 b 업데이트 및 학습과정 결과

W =  [[0.34134788]
 [0.94490112]
 [0.34002804]] , W.shape =  (3, 1) , b =  [0.94748035] , b.shape =  (1,)


In [83]:
learning_rate = 1e-5

f = lambda x : loss_func(x_data,t_data)

print("Initial loss value = ", loss_func(x_data, t_data))

for step in range(30001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    if (step % 3000 == 0):
        print("step = ", step, "loss value = ", loss_func(x_data, t_data))

Initial loss value =  952.5963060404089
step =  0 loss value =  388.76740963291934
step =  3000 loss value =  5.491084833782271
step =  6000 loss value =  4.278741414052048
step =  9000 loss value =  3.8898519968808034
step =  12000 loss value =  3.752120123965696
step =  15000 loss value =  3.701765936751281
step =  18000 loss value =  3.683078244996137
step =  21000 loss value =  3.6759979225959745
step =  24000 loss value =  3.67318564007734
step =  27000 loss value =  3.671944394216574
step =  30000 loss value =  3.671281965789819


In [84]:
test_data = np.array([100, 98, 81])
predict(test_data)

array([179.3569961])